Feature: User Login # features/login.feature:1

  @valid_login
  Scenario: Successful login                  # features/login.feature:3
    Given the OpenFin application is launched # steps/login_steps.py:12
    When I enter valid credentials            # steps/login_steps.py:18
    Then I should be logged in successfully   # steps/login_steps.py:42

  @invalid_login
  Scenario: Unsuccessful login with invalid credentials  # features/login.feature:9
    Given the OpenFin application is launched            # steps/login_steps.py:12
    When I enter invalid credentials                     # steps/login_steps.py:27
    Then I should see an error message                   # steps/login_steps.py:69
      Traceback (most recent call last):
        File "C:\Automation\automation_suite\venv\Lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
          ~~~~~~~~~^^^^^^^^^^^^^^^^
        File "C:\Automation\automation_suite\venv\Lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
          ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "steps\login_steps.py", line 71, in step_impl
          if not context.login_window:
                 ^^^^^^^^^^^^^^^^^^^^
        File "C:\Automation\automation_suite\venv\Lib\site-packages\behave\runner.py", line 321, in __getattr__
          raise AttributeError(msg)
      AttributeError: 'Context' object has no attribute 'login_window'
      
      Captured logging:
      INFO:builtins:Launching the OpenFin application...
      INFO:automation:Launching OpenFin application...
      INFO:automation:Waiting for the Mizuho login window to appear...
      INFO:automation:Found window: Mizuho Front Office
      INFO:builtins:OpenFin application launched.
      INFO:builtins:Entering invalid credentials...
      INFO:automation:Found window: Mizuho Front Office
      INFO:automation:Filling in login credentials...
      INFO:automation:Login attempt made.
      INFO:builtins:Invalid credentials entered.
      INFO:automation:Actual error message: Login failed. Incorrect username and/or password OR Invalid/missing access token
      INFO:automation:Error message validated successfully.
      INFO:builtins:Error message validated successfully.


